name: herebedragons-studios/ts-logging
on:
  push:
    branches: [ master ]
    pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:18
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3
          with:
            node-version: 18
      - uses: actions/cache@v3.3.2
        with:
          path: |-
            node_modules/
            .npm/
          key: dependencies-${{ github.ref }}-${{ github.workspace }}${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci --cache .npm --prefer-offline

  build:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:18
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/cache@v3.3.2
        with:
          restore-keys: |
            dependencies-${{ github.ref }}-${{ github.workspace }}${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v3.3.2
        with:
          path: |-
            dist/
            lib/
          key: build-$CI_JOB_IMAGE-${{ github.ref }}
      - run: npm run build:prod

  tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:18
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/cache@v3.3.2
        with:
          restore-keys: |
            dependencies-${{ github.ref }}-${{ github.workspace }}${{ hashFiles('**/package-lock.json') }}
            build-$CI_JOB_IMAGE-${{ github.ref }}
      - uses: actions/cache@v3.3.2
        with:
          path: workdocs/coverage/
          key: test-$CI_JOB_IMAGE-${{ github.ref }}
      - run: npm run test:ci
  #     # 'artifacts.junit' was not transformed because there is no suitable equivalent in GitHub Actions
  #     # 'coverage' was not transformed because there is no suitable equivalent in GitHub Actions.

  npm-deploy:
    needs:
      - tests
      - build
    runs-on: ubuntu-latest
    container:
      image: node:18
    if: (startsWith(github.ref, 'refs/tags')) && !(startsWith(github.ref, 'refs/heads'))
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/cache@v3.3.2
        with:
          restore-keys: |
            dependencies-${{ github.ref }}-${{ github.workspace }}${{ hashFiles('**/package-lock.json') }}
            build-$CI_JOB_IMAGE-${{ github.ref }}
      - uses: actions/download-artifact@v3.0.2
      - run: echo "Attempting to publish package ${NPM_PACKAGE_NAME} version ${NPM_PACKAGE_VERSION} to NPM registry."
      - run: echo "//${{ github.server_url }}/api/v4/projects/${{ github.repository }}/packages/npm/:_authToken=${{ github.token }}" > .npmrc
      - run: npm publish

  pages:
    needs: tests
    runs-on: ubuntu-latest
    container:
      image: node:18
    timeout-minutes: 60
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/cache@v3.3.2
        with:
          restore-keys: |
            dependencies-${{ github.ref }}-${{ github.workspace }}${{ hashFiles('**/package-lock.json') }}
            test-$CI_JOB_IMAGE-${{ github.ref }}
      - uses: actions/download-artifact@v3.0.2
      - run: npm ci --cache .npm --prefer-offline
      - run: npm run docs
      - run: mv docs public
      - uses: actions/upload-artifact@v3.1.3
        if: success()
        with:
          name: "${{ github.job }}"
          path: public
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: public
