# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Setting up node and npmrc
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Restoring Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules/
            .npm/
          key: dependencies-${{ github.ref }}
      - name: Restoring built solution...
        uses: actions/cache@v3
        with:
          path: |
            dist/
            lib/
          key: build-${{ github.ref }}
      - name: Publishing to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
